version: '3.3'
services:
  mango:
    ports:
      - '27017:27017'
    container_name: fight_micro_service_mongo
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    image: mongo
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
